### ISSUE TITLE
Returns current working directory + relative path with here()

### ISSUE THREAD

**Issue by aseyedia** [wildland-creative/pyhere#10] opened 2024-01-03 16:07 UTC
Hi,

Firstly, thank you so much for developing this. I appreciate having an equivalent to R's `here` in Python.

When I try to use pyhere's `here`, I am instead returned the concatenation of the current working directory and the relative path to the desired directory/file:

```python
>>> here(f"flows/02_gcp/data/yellow/yellow_tripdata_2021_01.parquet")
PosixPath('/Users/artas/GithubProjects/DE-Zoomcamp-FollowAlong/week_2_workflow_orchestration/flows/03-deployments/../../../flows/02_gcp/data/yellow/yellow_tripdata_2021_01.parquet')
```

Strictly speaking, I don't expect this to cause any problems, but I was wondering why it doesn't cleanly display the relative path from the project root directory. There are, as far as I can tell, no root indicators in `03-deployments/`. I added a `.here` to root dir even though it already had a `.git` but that didn't change anything.

Anyway, not really causing a problem, was just curious.

Thanks!

**Comment by geotheory** [comment] 2024-07-26 11:01
@joshpsawyer could you possibly clarify if you're still maintaining this very useful library? If not perhaps someone else will be able to step up.

**Comment by joshpsawyer** [comment] 2024-07-26 15:10
Hi @geotheory and @aseyedia - yep, still maintaining it, tbh I didn't realize anybody was using it aside from me

@aseyedia : good question, and I don't know why, as I'm calling `resolve()` on the resulting path... let me recreate it and see if I can figure out what's going on.

@geotheory : do you have the same question or something else?

**Comment by joshpsawyer** [comment] 2024-07-26 15:36
@aseyedia I'm not able to recreate this issue, it's resolving to the full path on Windows and Ubuntu. Do you have a minimal reproducible example?

**Comment by joshpsawyer** [comment] 2024-07-26 15:41
Oh, it's because I'm calling `resolve()` on the root but not the root concatenated with the passed string. New version forthcoming

**Comment by joshpsawyer** [comment] 2024-07-26 19:01
@aseyedia v1.0.3 in pip, please update, issue's no longer present

**Closed by joshpsawyer** 2024-07-26 19:01 UTC

**Comment by aseyedia** [comment] 2024-07-27 14:46
Amazing! Thank you!

**Comment by geotheory** [comment] 2024-07-29 10:39
> @geotheory : do you have the same question or something else?

Yes the same. Thanks for resolving. And thanks agai for making this - it's so simple and useful.
